# Generated by Django 6.0.5 on 2026-05-25 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_id', models.CharField(help_text='Unique ID from Gmail API — prevents duplicate fetching', max_length=200, unique=True)),
                ('sender_name', models.CharField(blank=True, max_length=300)),
                ('sender_email', models.EmailField(blank=True, max_length=300)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('body_preview', models.TextField(blank=True, help_text='First 500 chars of email body')),
                ('body_full', models.TextField(blank=True, help_text='Full email body text')),
                ('received_at', models.DateTimeField(blank=True, help_text='When the email was originally sent', null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True, help_text='When we pulled it from Gmail')),
                ('is_read', models.BooleanField(default=False)),
                ('is_scam', models.BooleanField(blank=True, help_text='True=scam, False=safe, None=not analyzed yet', null=True)),
                ('scam_confidence', models.FloatField(blank=True, help_text='0.0 to 1.0 — how confident the model is', null=True)),
                ('scam_reasons', models.TextField(blank=True, help_text='JSON list of reasons why flagged as scam')),
                ('opportunity_type', models.CharField(blank=True, choices=[('scholarship', 'Scholarship'), ('internship', 'Internship'), ('job', 'Job'), ('competition', 'Competition'), ('workshop', 'Workshop'), ('other', 'Other'), ('none', 'Not an Opportunity')], help_text='Category of opportunity (if any)', max_length=50)),
                ('relevance_score', models.FloatField(blank=True, help_text='0.0 to 10.0 — how relevant to this student', null=True)),
                ('deadline', models.DateField(blank=True, help_text='Application deadline if found in email', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
                'ordering': ['-received_at'],
            },
        ),
    ]
