# Generated by Django 4.2.7 on 2026-06-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='flagged_reason',
            field=models.TextField(blank=True, help_text="User's reason for flagging the email"),
        ),
        migrations.AddField(
            model_name='email',
            name='is_flagged',
            field=models.BooleanField(default=False, help_text='User manually flagged this email as scam/suspicious'),
        ),
        migrations.AddField(
            model_name='email',
            name='scam_severity',
            field=models.CharField(blank=True, default='', help_text='Comma-separated severity flags (high, medium, low)', max_length=100),
        ),
    ]
