# Generated by Django 4.2.7 on 2026-06-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_email_flagged_reason_email_is_flagged_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='flagged_reason',
            field=models.TextField(blank=True, default='', help_text="User's reason for flagging the email", null=True),
        ),
    ]
